apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ui-deploy-
spec:
  serviceAccountName: quay-login
  pipelineRef:
    name: ui-pipeline
  params:
    - name: IMAGE
      value: quay.io/vinamra2807/ui
    - name: TAG
      value: v1
    - name: HUB_NAMESPACE
      value: tekton-hub
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
    - name: kubeconfig-dir
      configMap:
        name: kubeconfig
    - name: token
      configMap:
        name: tokens-configmap
