apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: api
spec:
  serviceAccountName: quay-login
  params:
    - name: IMAGE
      value: quay.io/vinamra2807/cicd-api
    - name: TAG
      value: v1
    - name: HUB_NAMESPACE
      value: tekton-hub
    - name: k8S_VARIANT #it will accept either openshift or kubernetes
      value: openshift
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
    - name: kubeconfig-dir
      configMap:
        name: kubeconfig
    - name: token
      configMap:
        name: tokens-configmap
  pipelineRef:
    name: api-deploy
